### ISSUE TITLE
AttributeError: 'PointCloud' object has no attribute 'to_msg'

### ISSUE THREAD

**Issue by snail-radar** [MapIV/pypcd4#4]
I follow the install instructions exactly and I get this error when trying to convert a PointCloud to a PointCloud2 message.
```
pc2_msg = pc.to_msg(header)
```

What can I do to fix this?

**Comment by urasakikeisuke** [comment]
Thanks for reaching out. The issue you ran into was because the `to_msg` method was in testing when you tried it. It was pushed to GitHub, but not yet on PyPI.

We've now published it on PyPI, so the error should be fixed. To get the latest version of the package, you can run:

```bash
pip install -U pypcd4
```

Thanks for your patience and let us know if you run into anything else!
